<header>
<!-- This menu is used for easy navigation across all pages -->
        <h1> People Health Pharmacy </h1>
        <nav id="navbar"> 
            <p class="menu" ><a href="index.php">Home</a></p> 
            <p class="menu" ><a href="add.php">Add a sales record</a></p>
            <p class="menu" ><a href="edit.php">Edit a sales record</a></p>
            <p class="menu" ><a href="show.php">Browse sales records</a></p>
        </nav>
   </header>