<header>
<!-- This menu is used for easy navigation across all pages -->
        <nav> 
            <p class="menu" ><a href="index.php">Home</a></p> 
            <p class="menu" ><a href="add.php">Add a sales record</a></p>
            <p class="menu" ><a href="edit.php">Edit a sales record</a></p>
            <p class="menu" ><a href="show.php">Browse sales records</a></p>
            <p class="menu" ><a href="displaymonthly.php">Display Monthly</a></p>
        </nav>
   </header>