<header>
<!-- This menu is used for easy navigation across all pages -->
        <nav> 
            <p class="menu" ><a href="index.php">Home</a></p> 
            <p class="menu" ><a href="add.php">Add a sales record</a></p>
            <p class="menu" ><a href="edit.php">Edit a sales record</a></p>
            <p class="menu" ><a href="show.php">Browse sales records</a></p>
            <p class="menu" ><a href="displayreport.php">Generate a report</a></p>
            <p class="menu" ><a href="addproduct.php">Add a product</a></p>
            <p class="menu" ><a href="editproduct.php">Edit a product</a></p>
        </nav>
   </header>